"""add railway network edge topological trussness

Revision ID: 02096900f294
Revises: 7765476a0c28
Create Date: 2026-09-30 18:59:37.864297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02096900f294'
down_revision: Union[str, Sequence[str], None] = '7765476a0c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railway_network_edge_topological_trussness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_build_id', sa.Integer(), nullable=False),
    sa.Column('timetable_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('station_a_id', sa.Integer(), nullable=False),
    sa.Column('station_b_id', sa.Integer(), nullable=False),
    sa.Column('trussness', sa.Integer(), nullable=False),
    sa.Column('triangle_support', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('station_a_id < station_b_id', name='ck_edge_trussness_station_order'),
    sa.ForeignKeyConstraint(['graph_build_id'], ['railway_graph_builds.id'], ),
    sa.ForeignKeyConstraint(['station_a_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['station_b_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['timetable_snapshot_id'], ['dataset_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_build_id', 'station_a_id', 'station_b_id', name='uq_railway_network_edge_trussness_build_stations')
    )
    op.create_index('ix_railway_edge_trussness_build_stations', 'railway_network_edge_topological_trussness', ['graph_build_id', 'station_a_id', 'station_b_id'], unique=False)
    op.create_index('ix_railway_edge_trussness_snapshot', 'railway_network_edge_topological_trussness', ['timetable_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_railway_edge_trussness_snapshot', table_name='railway_network_edge_topological_trussness')
    op.drop_index('ix_railway_edge_trussness_build_stations', table_name='railway_network_edge_topological_trussness')
    op.drop_table('railway_network_edge_topological_trussness')
    # ### end Alembic commands ###
