"""add railway network edge topological biconnected component

Revision ID: 2c221ff12478
Revises: 410d365bb0e0
Create Date: 2026-09-30 20:53:44.023950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c221ff12478'
down_revision: Union[str, Sequence[str], None] = '410d365bb0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railway_network_edge_topological_biconnected_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_build_id', sa.Integer(), nullable=False),
    sa.Column('timetable_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('station_a_id', sa.Integer(), nullable=False),
    sa.Column('station_b_id', sa.Integer(), nullable=False),
    sa.Column('block_edge_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('station_a_id < station_b_id', name='ck_edge_biconnected_comp_station_order'),
    sa.ForeignKeyConstraint(['graph_build_id'], ['railway_graph_builds.id'], ),
    sa.ForeignKeyConstraint(['station_a_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['station_b_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['timetable_snapshot_id'], ['dataset_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_build_id', 'station_a_id', 'station_b_id', name='uq_edge_biconnected_comp_graph_a_b')
    )
    op.create_index('ix_edge_biconnected_comp_graph_a_b', 'railway_network_edge_topological_biconnected_component', ['graph_build_id', 'station_a_id', 'station_b_id'], unique=False)
    op.create_index('ix_edge_biconnected_comp_snapshot', 'railway_network_edge_topological_biconnected_component', ['timetable_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_edge_biconnected_comp_snapshot', table_name='railway_network_edge_topological_biconnected_component')
    op.drop_index('ix_edge_biconnected_comp_graph_a_b', table_name='railway_network_edge_topological_biconnected_component')
    op.drop_table('railway_network_edge_topological_biconnected_component')
    # ### end Alembic commands ###
