"""add_railway_station_topological_coreness

Revision ID: 7765476a0c28
Revises: b3b98392bc7b
Create Date: 2026-09-30 16:48:01.737819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7765476a0c28'
down_revision: Union[str, Sequence[str], None] = 'b3b98392bc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railway_station_topological_coreness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_build_id', sa.Integer(), nullable=False),
    sa.Column('timetable_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('coreness', sa.Integer(), nullable=False),
    sa.Column('degree', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_build_id'], ['railway_graph_builds.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['timetable_snapshot_id'], ['dataset_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_build_id', 'station_id', name='uq_railway_station_topological_coreness_build_station')
    )
    op.create_index('ix_railway_station_coreness_build_station', 'railway_station_topological_coreness', ['graph_build_id', 'station_id'], unique=False)
    op.create_index('ix_railway_station_coreness_snapshot', 'railway_station_topological_coreness', ['timetable_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_railway_station_coreness_snapshot', table_name='railway_station_topological_coreness')
    op.drop_index('ix_railway_station_coreness_build_station', table_name='railway_station_topological_coreness')
    op.drop_table('railway_station_topological_coreness')
    # ### end Alembic commands ###
