"""correct_provenance

Revision ID: 80effcab47db
Revises: 74d724cc4493
Create Date: 2026-09-26 10:24:00.557344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "80effcab47db"
down_revision: Union[str, Sequence[str], None] = "74d724cc4493"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "station_observations",
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=255), nullable=True),
        sa.Column("zone", sa.String(length=50), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["dataset_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "station_id"),
    )
    op.drop_constraint(op.f("stations_snapshot_id_fkey"), "stations", type_="foreignkey")
    op.drop_column("stations", "name")
    op.drop_column("stations", "updated_at")
    op.drop_column("stations", "longitude")
    op.drop_column("stations", "latitude")
    op.drop_column("stations", "state")
    op.drop_column("stations", "snapshot_id")
    op.drop_column("stations", "zone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stations", sa.Column("zone", sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.add_column(
        "stations", sa.Column("snapshot_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "stations", sa.Column("state", sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.add_column(
        "stations",
        sa.Column(
            "latitude", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "stations",
        sa.Column(
            "longitude", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "stations",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "stations", sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        op.f("stations_snapshot_id_fkey"), "stations", "dataset_snapshots", ["snapshot_id"], ["id"]
    )
    op.drop_table("station_observations")
    # ### end Alembic commands ###
