"""add train timetable foundation

Revision ID: aeb7920d31bb
Revises: 80effcab47db
Create Date: 2026-09-26 11:09:56.276001

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aeb7920d31bb"
down_revision: str | Sequence[str] | None = "80effcab47db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trains",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trains_number"), "trains", ["number"], unique=True)
    op.create_table(
        "train_observations",
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("train_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("return_train_number", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["dataset_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["train_id"],
            ["trains.id"],
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "train_id"),
    )
    op.create_table(
        "train_stop_observations",
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("train_id", sa.Integer(), nullable=False),
        sa.Column("stop_sequence", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("arrival_time", sa.String(length=20), nullable=True),
        sa.Column("departure_time", sa.String(length=20), nullable=True),
        sa.Column("source_day", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["dataset_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["train_id"],
            ["trains.id"],
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "train_id", "stop_sequence"),
    )
    op.create_index(
        op.f("ix_train_stop_observations_station_id"),
        "train_stop_observations",
        ["station_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_train_stop_observations_station_id"), table_name="train_stop_observations"
    )
    op.drop_table("train_stop_observations")
    op.drop_table("train_observations")
    op.drop_index(op.f("ix_trains_number"), table_name="trains")
    op.drop_table("trains")
    # ### end Alembic commands ###
