"""add railway_network_edge_resilience

Revision ID: b3b98392bc7b
Revises: f93f53f2844b
Create Date: 2026-09-30 16:00:16.874957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b98392bc7b'
down_revision: Union[str, Sequence[str], None] = 'f93f53f2844b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railway_network_edge_resilience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_build_id', sa.Integer(), nullable=False),
    sa.Column('timetable_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('station_a_id', sa.Integer(), nullable=False),
    sa.Column('station_b_id', sa.Integer(), nullable=False),
    sa.Column('detour_distance', sa.Integer(), nullable=True),
    sa.Column('detour_exists', sa.Boolean(), nullable=False),
    sa.Column('is_structural_bridge', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['graph_build_id'], ['railway_graph_builds.id'], ),
    sa.ForeignKeyConstraint(['station_a_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['station_b_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['timetable_snapshot_id'], ['dataset_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_resilience_build', 'railway_network_edge_resilience', ['graph_build_id'], unique=False)
    op.create_index('ix_edge_resilience_lookup', 'railway_network_edge_resilience', ['graph_build_id', 'station_a_id', 'station_b_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_edge_resilience_lookup', table_name='railway_network_edge_resilience')
    op.drop_index('ix_edge_resilience_build', table_name='railway_network_edge_resilience')
    op.drop_table('railway_network_edge_resilience')
    # ### end Alembic commands ###
