"""add referential integrity constraint to train stop observations

Revision ID: c49bf45840dc
Revises: fbb1fb02eb78
Create Date: 2026-09-26 11:22:00.796021

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c49bf45840dc"
down_revision: str | Sequence[str] | None = "fbb1fb02eb78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_train_stop_obs_train_obs",
        "train_stop_observations",
        "train_observations",
        ["snapshot_id", "train_id"],
        ["snapshot_id", "train_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_train_stop_obs_train_obs", "train_stop_observations", type_="foreignkey")
    # ### end Alembic commands ###
