"""add journey search indexes

Revision ID: deedd587528e
Revises: c49bf45840dc
Create Date: 2026-09-26 11:49:17.125377

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "deedd587528e"
down_revision: str | Sequence[str] | None = "c49bf45840dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_train_stops_snapshot_station",
        "train_stop_observations",
        ["snapshot_id", "station_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_train_stops_snapshot_station", table_name="train_stop_observations")
    # ### end Alembic commands ###
