"""feat: railway graph foundation

Revision ID: f93f53f2844b
Revises: deedd587528e
Create Date: 2026-09-26 13:55:31.023805

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f93f53f2844b"
down_revision: Union[str, Sequence[str], None] = "deedd587528e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "railway_graph_builds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timetable_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["timetable_snapshot_id"],
            ["dataset_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("timetable_snapshot_id"),
    )
    op.create_table(
        "railway_network_edges",
        sa.Column("timetable_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("from_station_id", sa.Integer(), nullable=False),
        sa.Column("to_station_id", sa.Integer(), nullable=False),
        sa.Column("train_count", sa.Integer(), nullable=False),
        sa.Column("min_duration_minutes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_station_id"],
            ["stations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["timetable_snapshot_id"],
            ["dataset_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_station_id"],
            ["stations.id"],
        ),
        sa.PrimaryKeyConstraint("timetable_snapshot_id", "from_station_id", "to_station_id"),
    )
    op.create_index(
        "ix_network_edges_from_station",
        "railway_network_edges",
        ["timetable_snapshot_id", "from_station_id"],
        unique=False,
    )
    op.create_index(
        "ix_network_edges_to_station",
        "railway_network_edges",
        ["timetable_snapshot_id", "to_station_id"],
        unique=False,
    )
    op.create_table(
        "railway_service_edges",
        sa.Column("timetable_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("train_id", sa.Integer(), nullable=False),
        sa.Column("from_stop_sequence", sa.Integer(), nullable=False),
        sa.Column("from_station_id", sa.Integer(), nullable=False),
        sa.Column("to_station_id", sa.Integer(), nullable=False),
        sa.Column("to_stop_sequence", sa.Integer(), nullable=False),
        sa.Column("departure_time", sa.String(length=20), nullable=True),
        sa.Column("arrival_time", sa.String(length=20), nullable=True),
        sa.Column("source_day_offset", sa.Integer(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_station_id"],
            ["stations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["timetable_snapshot_id"],
            ["dataset_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_station_id"],
            ["stations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["train_id"],
            ["trains.id"],
        ),
        sa.PrimaryKeyConstraint("timetable_snapshot_id", "train_id", "from_stop_sequence"),
    )
    op.create_index(
        "ix_service_edges_from_station",
        "railway_service_edges",
        ["timetable_snapshot_id", "from_station_id"],
        unique=False,
    )
    op.create_index(
        "ix_service_edges_to_station",
        "railway_service_edges",
        ["timetable_snapshot_id", "to_station_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_service_edges_to_station", table_name="railway_service_edges")
    op.drop_index("ix_service_edges_from_station", table_name="railway_service_edges")
    op.drop_table("railway_service_edges")
    op.drop_index("ix_network_edges_to_station", table_name="railway_network_edges")
    op.drop_index("ix_network_edges_from_station", table_name="railway_network_edges")
    op.drop_table("railway_network_edges")
    op.drop_table("railway_graph_builds")
    # ### end Alembic commands ###
