"""increase return_train_number length

Revision ID: fbb1fb02eb78
Revises: aeb7920d31bb
Create Date: 2026-09-26 11:15:51.682839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fbb1fb02eb78"
down_revision: Union[str, Sequence[str], None] = "aeb7920d31bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "train_observations",
        "return_train_number",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "train_observations",
        "return_train_number",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
